[versions]
kotlin = "1.7.10"
java-target = "1.8"

# Note: there are some compose/androidx versions left hardcoded in `paparazzi/paparazzi/build.gradle`,
# because they refer to JAR files names in the `paparazzi/paparazzi/libs` folder.

compose-compiler = "1.3.0"

ktlint = "0.46.1"
# Maps to this commit: https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+/fa3aa65
# which runs on JDK 11.
layoutLibPrebuiltSha = 'fa3aa65'
layoutlib = "2021.2.1-patch1-fa3aa65"

moshi = "1.13.0"
jcodec = "0.2.5"
bytebuddy = "1.12.10"

[libraries]
layoutlib-native-jdk11 = { module = "app.cash.paparazzi:layoutlib-native-jdk11", version.ref = "layoutlib" }
layoutlib-native-macArm = { module = "app.cash.paparazzi:layoutlib-native-macarm", version.ref = "layoutlib" }
layoutlib-native-macOsX = { module = "app.cash.paparazzi:layoutlib-native-macosx", version.ref = "layoutlib" }
layoutlib-native-windows = { module = "app.cash.paparazzi:layoutlib-native-win", version.ref = "layoutlib" }
layoutlib-native-linux = { module = "app.cash.paparazzi:layoutlib-native-linux", version.ref = "layoutlib" }

tools-common = { module = "com.android.tools:common", version = "27.1.2" }
tools-layoutlib = { module = "com.android.tools.layoutlib:layoutlib-api", version = "27.2.2" }
tools-ninepatch = { module = "com.android.tools:ninepatch", version = "30.1.2" }
tools-sdkCommon = { module = "com.android.tools:sdk-common", version = "26.6.4" }

androidx-annotations = { module = "androidx.annotation:annotation", version = "1.3.0" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
composeUi-material = { module = "androidx.compose.material:material", version = "1.2.1" }
androidx-lifecycleCommon = { module = "androidx.lifecycle:lifecycle-common", version = "2.4.0" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }

guava = { module = "com.google.guava:guava", version = "31.0.1-jre" }
kxml2 = { module = "kxml2:kxml2", version = "2.3.0" }
okio = { module = "com.squareup.okio:okio", version = "3.1.0" }

moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

jcodec-core = { module = "org.jcodec:jcodec", version.ref = "jcodec" }
jcodec-javase = { module = "org.jcodec:jcodec-javase", version.ref = "jcodec" }
bytebuddy-agent = { module = "net.bytebuddy:byte-buddy-agent", version.ref = "bytebuddy" }
bytebuddy-core = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }

junit = { module = "junit:junit", version = "4.13.2" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.8" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
assertj = { module = "org.assertj:assertj-core", version = "3.23.1" }

plugin-android = { module = "com.android.tools.build:gradle", version = "7.1.2" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "kotlin" }
plugin-grgit = { module = "org.ajoberstar.grgit:grgit-gradle", version = "5.0.0" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.21.0" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.8.0" }
plugin-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.42.0" }
