[versions]
agp = "7.1.2"
bytebuddy = "1.12.10"
jcodec = "0.2.5"
kotlin = "1.7.10"
moshi = "1.13.0"

[libraries]
# Gradle plugins
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.7.10" }
plugin-grgit = { module = "org.ajoberstar.grgit:grgit-gradle", version= "5.0.0" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.21.0" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.8.0" }
plugin-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.42.0" }

# Regular dependencies
androidx-annotations = { module = "androidx.annotation:annotation", version = "1.3.0" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version = "1.3.0" }
androidx-compose-ui-material = { module = "androidx.compose.material:material", version = "1.2.1" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version = "2.4.0" }
assertj = { module = "org.assertj:assertj-core", version = "3.23.1" }
bytebuddy-agent = { module = "net.bytebuddy:byte-buddy-agent", version.ref = "bytebuddy" }
bytebuddy-core = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
guava =  { module = "com.google.guava:guava", version = "31.0.1-jre" }
jcodec-core = { module = "org.jcodec:jcodec", version.ref = "jcodec" }
jcodec-javase = { module = "org.jcodec:jcodec-javase", version.ref = "jcodec" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }
kxml2 = { module = "kxml2:kxml2", version = "2.3.0" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.8" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
tools-common = { module = "com.android.tools:common", version = "27.1.2" }
tools-layoutlib = { module = "com.android.tools.layoutlib:layoutlib-api", version = "27.2.2" }
tools-ninepatch = { module = "com.android.tools:ninepatch", version = "30.1.2" }
tools-sdkCommon = { module = "com.android.tools:sdk-common", version = "26.6.4" }
okio = { module = "com.squareup.okio:okio", version = "3.1.0" }
